inference:
  # Use this to write with date-time stamp.
  name: ${now:%Y-%m-%d}_${now:%H-%M}
  seed: 123
  ckpt_path: ./weights/pretrained.ckpt
  output_dir: inference_outputs/
  use_gpu: True
  num_gpus: 1

  samples:
    validset_path: ./inference/valid_seq.csv
    esm_savepath: ${inference.output_dir}
    sample_num: 250
    sample_batch: 5

